DROP TABLE DEPENTMENT CASCADE CONSTRAINTS PURGE;
CREATE TABLE DEPENTMENT(
    ID_DEP CHAR(4) NOT NULL ENABLE,
    NAME_DEP VARCHAR2(20),
    EMP_LEAD CHAR(4),
    CONSTRAINT "DEPENTMENT_PK" PRIMARY KEY ("ID_DEP")
);


DROP TABLE POSITION CASCADE CONSTRAINTS PURGE;
CREATE TABLE POSITION(
    ID_PST char(4) NOT NULL ENABLE,
    NAME_PST VARCHAR2(20),
    JOB_DETEL varchar2(20),
    CONSTRAINT "POSITION_PK" PRIMARY KEY ("ID_PST")
);


DROP TABLE PERMISSION CASCADE CONSTRAINTS PURGE;
CREATE TABLE PERMISSION (
    ID_PERM CHAR(4) NOT NULL ENABLE,
    NAME_PERM VARCHAR2(20),
    NUM_PERM VARCHAR2(20),
    CONSTRAINT "PERMISSION_PK" PRIMARY KEY ("ID_PERM")
);

DROP TABLE EMPLOYEE CASCADE CONSTRAINTS PURGE;
CREATE TABLE EMPLOYEE(
    ID_EMP  CHAR(4) NOT NULL ENABLE,
    NAME VARCHAR2(20), 
    L_NAME VARCHAR2(20), 
    B_DAY DATE, 
    SEX VARCHAR2(20), 
    SAL NUMBER(10), 
    ADDRESS VARCHAR2(20), 
    EMAIL VARCHAR2(20), 
    ID_POS VARCHAR2(20), 
    NATIONALITY VARCHAR2(20), 
    ID_LEAD CHAR(4), 
    USER_ID VARCHAR2(20), 
    PASSWORD VARCHAR2(20), 
    PERMIS CHAR(4),
    DEPNO CHAR(4), 
    PSTNO CHAR(4), 
    CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID_EMP")
);

DROP TABLE BASE_FEATUREAS CASCADE CONSTRAINTS PURGE;
CREATE TABLE BASE_FEATUREAS(
    ID_FEAT CHAR(5) NOT NULL ENABLE,
    NAME_FEAT VARCHAR2(20),
    CONSTRAINT "FEATUREAS_PD" PRIMARY KEY ("ID_FEAT")
);

DROP TABLE NEW_EMP CASCADE CONSTRAINTS PURGE;
CREATE TABLE NEW_EMP(
    ID_NEMP CHAR(4) NOT NULL ENABLE,
    NAME_NEMP VARCHAR2(20),
    LNAME_NEMP VARCHAR2(20),
    DAY_NEMP DATE,
    SEX_NEMP VARCHAR2(20),
    BDAY_NEMP DATE,
    NOTIONALITY_NEMP VARCHAR2(20),
    RACE_NEMP VARCHAR2(20),
    ADDRESS VARCHAR2(50),
    EMAIL VARCHAR2(20),
    ID_POS VARCHAR2(13),
    PATHDOC_NEMP VARCHAR2(50),
    RELIGION_NEMP VARCHAR2(20),
    CONSTRAINT "NEW_EMP_PK" PRIMARY KEY ("ID_NEMP")
);

DROP TABLE SCORE_NEMP CASCADE CONSTRAINTS PURGE;
CREATE TABLE SCORE_NEMP (
    ORDER_SCORE NUMBER NOT NULL ENABLE,
    TECHINCAL NUMBER(2),
    LEANING NUMBER(2),
    CREATER NUMBER(2),
    HUM_RELA NUMBER(2),
    Y_N NUMBER(1),
    DETEL VARCHAR2(50),
    EMP_INTV CHAR(4),
    CONSTRAINT "ORDER_SCOER_PK" PRIMARY KEY ("ORDER_SCORE","EMP_INTV")
);

DROP TABLE LIST_FEATUREAS_POSITION CASCADE CONSTRAINTS PURGE;
CREATE TABLE LIST_FEATUREAS_POSITION(
    ORDER_FP NUMBER NOT NULL ENABLE,
    ID_POSITION CHAR(4),
    ID_FEATUREAS CHAR(4),
    DETEL VARCHAR2(50),
    CONSTRAINT "ORDER_F_PK" PRIMARY KEY ("ORDER_FP","ID_POSITION")
);

DROP TABLE LIST_NEMP_POS CASCADE CONSTRAINTS PURGE;
CREATE TABLE LIST_NEMP_POS(
    ORDER_NP NUMBER,
    ID_POSITION CHAR(4),
    POS_NEMP CHAR(4),
    SEL_NEED NUMBER(10),
    CONSTRAINT "ORDER_NP_PK" PRIMARY KEY ("ORDER_NP","POS_NEMP")
);

DROP TABLE REQUIRED_EMP CASCADE CONSTRAINTS PURGE;
CREATE TABLE REQUIRED_EMP(
    ID_REQ CHAR(4) NOT NULL ENABLE,
    DAYSAMVE_REQ VARCHAR2(20),
    DETEL_REQ VARCHAR(50),
    TYPE_REQ VARCHAR(20),
    NUM_REQ NUMBER(3),
    GET_REQ NUMBER(3),
    PST_REQ CHAR(4),
    EMP_EMP CHAR(4),
    CONSTRAINT "REQUIRED_EMP_PK" PRIMARY KEY ("ID_REQ")
);

DROP TABLE RECTUITMENT CASCADE CONSTRAINTS PURGE;
CREATE TABLE RECTUITMENT(
    ID_REC CHAR(4) NOT NULL ENABLE,
    DETEL_REC VARCHAR(50),
    DAY_REC DATE,
    REQ_REC CHAR(4),
    CONSTRAINT "RECTUITMENT_PK" PRIMARY KEY ("ID_REC")
);

DROP TABLE INTERVIEW CASCADE CONSTRAINTS PURGE;
CREATE TABLE INTERVIEW(
    ID_INVIEW CHAR(4) NOT NULL ENABLE,
    DAY_SELECT DATE,
    POS_INTERVIEW CHAR(4),
    CONSTRAINT "INTERVIEW_PK" PRIMARY KEY ("ID_INVIEW")
);

DROP TABLE DAY_CHOOSE CASCADE CONSTRAINTS PURGE;
CREATE TABLE DAY_CHOOSE(
    ORDER_INTV NUMBER(2),
    INTV CHAR(4),
    DAY_CHOOSE DATE,
    CONSTRAINT "ORDER_CHOOSE_PK" PRIMARY KEY ("ORDER_INTV","INTV")
);

DROP TABLE MEMBER_INTERVIEW CASCADE CONSTRAINTS PURGE;
CREATE TABLE MEMBER_INTERVIEW(
    ORDER_MEMBINTV NUMBER(2),
    INTV_EMP CHAR(4),
    DAY_SELECT DATE,
    CONSTRAINT "9RDER_MEMINTV_PK" PRIMARY KEY ("ORDER_MEMBINTV","INTV_EMP")
);
ALTER TABLE EMPLOYEE ADD CONSTRAINT PERMIS_EMP_FK FOREIGN KEY(PERMIS) REFERENCES PERMISSION(ID_PERM);
ALTER TABLE EMPLOYEE ADD CONSTRAINT DEP_EMP_FK FOREIGN KEY(DEPNO) REFERENCES DEPENTMENT(ID_DEP);
ALTER TABLE EMPLOYEE ADD CONSTRAINT PSTNO_EMP_FK FOREIGN KEY(PSTNO) REFERENCES POSITION(ID_PST);
ALTER TABLE LIST_FEATUREAS_POSITION ADD CONSTRAINT L_PST_FT_FK FOREIGN KEY(ID_POSITION) REFERENCES POSITION(ID_PST);
ALTER TABLE SCORE_NEMP ADD CONSTRAINT EMP_INTV_FK FOREIGN KEY(EMP_INTV) REFERENCES EMPLOYEE(ID_EMP);
ALTER TABLE LIST_NEMP_POS ADD CONSTRAINT POS_NEMP_FK FOREIGN KEY(POS_NEMP) REFERENCES NEW_EMP(ID_NEMP);
ALTER TABLE DAY_CHOOSE ADD CONSTRAINT INTV_FK FOREIGN KEY(INTV) REFERENCES INTERVIEW(ID_INVIEW);
ALTER TABLE MEMBER_INTERVIEW ADD CONSTRAINT INTV_EMP_FK FOREIGN KEY(INTV_EMP) REFERENCES EMPLOYEE(ID_EMP);
